# Generated by Django 5.2.13 on 2026-08-21 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código en mayúsculas (ej: RARA10)', max_length=50, unique=True)),
                ('descuento_porcentaje', models.IntegerField(default=0, help_text='Porcentaje de descuento (0-100)')),
                ('descuento_monto', models.IntegerField(default=0, help_text='Monto fijo de descuento en CLP')),
                ('activo', models.BooleanField(default=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Dejar en blanco para ilimitado', null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa_transporte',
            field=models.CharField(blank=True, default='', help_text='Ej: Starken, Chilexpress', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('EN_PREPARACION', 'En Preparación'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_seguimiento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='tienda.cupon'),
        ),
    ]
