# Generated by Django 5.2.13 on 2026-08-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_populate_producto_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('resumen', models.TextField(blank=True, help_text='Breve resumen para las tarjetas de blog')),
                ('contenido', models.TextField(help_text='Contenido completo del artículo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Artículo del Blog',
                'verbose_name_plural': 'Artículos del Blog',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_blog', models.BooleanField(default=False, help_text='Mostrar u ocultar la sección de Blog en la tienda')),
                ('mostrar_resenas', models.BooleanField(default=False, help_text='Mostrar u ocultar la sección de reseñas en los productos')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='ResenaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(blank=True, max_length=254)),
                ('calificacion', models.IntegerField(default=5, help_text='Calificación de 1 a 5 estrellas')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Reseña de Producto',
                'verbose_name_plural': 'Reseñas de Productos',
                'ordering': ['-fecha'],
            },
        ),
    ]
