# Generated by Django 5.2.13 on 2026-08-27 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_blogpost_configuracionsitio_resenaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_resena',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='resenaproducto',
            name='comprador_verificado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resenaproducto',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas_pedido', to='tienda.pedido'),
        ),
    ]
