# Generated by Django 5.2.13 on 2026-08-27 17:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_populate_pedido_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token_resena',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
