# Generated by Django 5.2.13 on 2026-08-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_alter_pedido_token_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='autor',
            field=models.CharField(blank=True, default='Rara Tienda', help_text='Nombre del autor del artículo (opcional)', max_length=100),
        ),
    ]
