# Generated by Django 5.2.13 on 2026-08-27 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_blogpost_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField(blank=True, help_text='ID del producto en la base de datos', null=True)),
                ('nombre_producto', models.CharField(help_text='Nombre del producto en el momento del evento', max_length=250)),
                ('accion', models.CharField(choices=[('CREACION', '🟢 Creación'), ('EDICION', '🔵 Edición'), ('TOGGLE', '🟡 Cambio de Estado'), ('ELIMINACION', '🔴 Eliminación')], max_length=20)),
                ('detalles', models.TextField(blank=True, help_text='Detalles o cambios registrados')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Producto',
                'verbose_name_plural': 'Logs de Productos',
                'ordering': ['-fecha'],
            },
        ),
    ]
