# Generated by Django 5.2.13 on 2026-08-27 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_populate_logproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logproducto',
            name='accion',
            field=models.CharField(choices=[('CREACION', '🟢 Creación'), ('EDICION', '🔵 Edición'), ('TOGGLE', '🟡 Cambio de Estado'), ('VENTA', '🛍️ Venta Realizada'), ('ELIMINACION', '🔴 Eliminación')], max_length=20),
        ),
        migrations.CreateModel(
            name='LogPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.IntegerField(blank=True, help_text='ID del pedido en la base de datos', null=True)),
                ('codigo_orden', models.CharField(help_text='Código de orden del pedido (ej: #1005)', max_length=50)),
                ('cliente_nombre', models.CharField(help_text='Nombre del cliente', max_length=150)),
                ('cliente_email', models.EmailField(blank=True, help_text='Email del cliente', max_length=254)),
                ('accion', models.CharField(choices=[('CREACION', '🟢 Pedido Creado'), ('PAGO_OK', '✅ Pago Confirmado'), ('ESTADO_CAMBIO', '🚚 Cambio de Estado'), ('SEGUIMIENTO', '📦 Datos de Seguimiento'), ('ERROR', '⚠️ Error / Fallo de Pago'), ('CANCELADO', '❌ Pedido Cancelado')], max_length=20)),
                ('detalles', models.TextField(blank=True, help_text='Detalles técnicos o resumen del evento')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario admin si la acción fue manual', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Pedido',
                'verbose_name_plural': 'Logs de Pedidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
