# Generated by Django 5.2.13 on 2026-08-29 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_populate_logpedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('visitas_humanos', models.PositiveIntegerField(default=0)),
                ('visitas_bots', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Métrica Diaria',
                'verbose_name_plural': 'Métricas Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetricaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Métrica de Producto',
                'verbose_name_plural': 'Métricas de Productos',
                'ordering': ['-fecha', '-vistas'],
                'unique_together': {('producto', 'fecha')},
            },
        ),
    ]
