# Generated by Django 5.2.13 on 2026-08-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_metricadiaria_metricaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='especie_dato_curioso',
            field=models.TextField(blank=True, help_text='Dato curioso o reseña educativa sobre la especie'),
        ),
        migrations.AddField(
            model_name='producto',
            name='especie_estado_conservacion',
            field=models.CharField(blank=True, help_text='Ej: Preocupación menor (LC), Vulnerable (VU)', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='especie_habitat',
            field=models.CharField(blank=True, help_text='Ej: Bosques templados y cordillera del sur de Chile', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='especie_nombre_cientifico',
            field=models.CharField(blank=True, help_text='Ej: Phrygilus patagonicus', max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='especie_nombre_comun',
            field=models.CharField(blank=True, help_text='Ej: Cometocino Patagónico, Amanita muscaria', max_length=150),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_ficha_especie',
            field=models.BooleanField(default=False, help_text='Marcar para incluir Ficha de Especie en la vista del producto'),
        ),
    ]
