# Generated by Django 5.2.13 on 2026-09-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(blank=True, help_text='Porcentaje de descuento (1-99)', null=True, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, help_text='Marcar para activar precio de oferta', verbose_name='En oferta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.IntegerField(blank=True, help_text='Nuevo precio rebajado en pesos', null=True, verbose_name='Precio de oferta'),
        ),
    ]
