# Generated by Django 5.2.13 on 2026-09-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_producto_descuento_porcentaje_producto_en_oferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='excluir_ofertas',
            field=models.BooleanField(default=False, help_text='No aplicar descuento sobre productos que ya estén en oferta'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='monto_minimo_compra',
            field=models.PositiveIntegerField(default=0, help_text='Monto mínimo en CLP para aplicar el cupón (0 = sin mínimo)'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='tope_maximo_descuento',
            field=models.PositiveIntegerField(blank=True, help_text='Tope máximo en CLP que puede descontar este cupón (dejar en blanco para ilimitado)', null=True),
        ),
    ]
