from .tienda_publica import (
    aplicar_ordenamiento,
    index,
    terminos_condiciones,
    categoria_detail,
    api_buscar_productos,
    producto_detail,
    producto_detail_by_id,
    blog_list,
    blog_detail,
    evaluar_compra,
    evaluar_producto_directo,
    agregar_resena,
)

from .checkout_pagos import (
    validar_rut_chileno,
    obtener_descuento_cupon,
    aplicar_cupon,
    quitar_cupon,
    agregar_al_carrito,
    ver_carrito,
    restar_del_carrito,
    quitar_del_carrito,
    limpiar_carrito,
    procesar_pedido,
    pedido_confirmado,
    webhook_mercadopago,
)

from .panel_admin import (
    CustomLoginView,
    panel_home,
    panel_productos,
    crear_producto,
    crear_categoria,
    toggle_producto,
    editar_producto,
    eliminar_producto,
    panel_pedidos,
    detalle_pedido,
    actualizar_estado_pedido,
    enviar_seguimiento_email,
    enviar_resena_email,
    confirmar_pago_pedido,
    panel_cupones,
    crear_cupon,
    editar_cupon,
    toggle_cupon,
    eliminar_cupon,
    exportar_pedidos_excel,
    exportar_stock_excel,
    panel_configuracion,
    panel_blog,
    crear_blog_post,
    editar_blog_post,
    eliminar_blog_post,
    panel_resenas,
    toggle_resena,
    eliminar_resena,
    panel_guia,
)

from .juegos_api import (
    menu_juegos,
    quien_es_esta_ave,
    memorice,
    letras_locas,
    minijuego,
    rosco,
    aves_en_tu_zona,
    radar_realtime,
    generar_avistamientos_fallback,
    ebird_proxy,
    get_species_dict,
)
